theme = "rose_pine"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
j = { k = "normal_mode" }
k = { j = "normal_mode" }

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
