theme = "rose_pine_moon"

[editor]
idle-timeout = 0
whitespace.render = "all"
indent-guides.render = true
rulers = [80]
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
X = "extend_line_above"
A-w = "extend_next_word_start"
A-b = "extend_prev_word_start"
A-e = "extend_next_word_end"
A-W = "extend_next_long_word_start"
A-B = "extend_prev_long_word_start"
A-E = "extend_next_long_word_end"
A-h = "extend_char_left"
A-j = "extend_line_down"
A-k = "extend_line_up"
A-l = "extend_char_right"
g = { k = ":buffer-close" }

[keys.insert]
j = { k = "normal_mode" }
C-space = "completion"
A-h = "move_char_left"
A-j = "move_line_down"
A-k = "move_line_up"
A-l = "move_char_right"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"